import = [
  "~/.config/alacritty/gruvbox_material_hard_dark.toml",
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true
padding = { x = 5, y = 5 }

[font]
size = 14.0
normal = { family = "JetBrains Mono Nerd Font", style = "regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "bold" }
